include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    sort_pub_dependencies: false
    argument_type_not_assignable: false
    public_member_api_docs: false
    strict_raw_type: false
    one_member_abstracts: false
    