include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    sort_pub_dependencies: false
    public_member_api_docs: false
    one_member_abstracts: false
    unawaited_futures: false
    avoid_bool_literals_in_conditional_expressions: false
    avoid_dynamic_calls: false
    inference_failure_on_function_invocation: false