name: ontari_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.3
  flutter_svg: ^1.1.6
  flutter_screenutil: ^5.7.0
  dio: ^5.1.1
  get_it: ^7.2.0
  injectable: ^2.1.1
  json_annotation: ^4.8.0
  get: ^4.6.5
  equatable: ^2.0.5
  firebase_core: ^2.8.0
  firebase_crashlytics: ^3.0.17
  dartz: ^0.10.1
  formz: ^0.5.0+1
  logger: ^1.3.0
  firebase_auth: ^4.3.0
  flutter: 
    sdk: flutter
  flutter_localization: ^0.1.10

dev_dependencies: 
  build_runner: ^2.3.3
  flutter_flavorizr: ^2.1.6
  very_good_analysis: ^3.0.2
  json_serializable: ^6.6.1
  injectable_generator: ^2.1.5
  flutter_test:
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/locales/
flutter_native_splash:
  color: '#193D71'
  image: assets/images/ic_app_icon_large.png
  android_screen_orientation: locked
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/ic_app_icon.png"
  min_sdk_android: 21

flavorizr:
  app:
    android:
      flavorDimensions: flavor-type
    ios:
  ide: "vscode"
  flavors:
    prod:
      app:
        name: Ontari-Prod
        icon: assets/images/ic_app_icon.png
      android:
        applicationId: com.prod.ontari
      ios:
        bundleId: com.prod.ontari
    dev:
      app:
        name: Ontari-Dev
        icon: assets/images/ic_app_icon.png
      android:
        applicationId: com.dev.ontari
      ios:
        bundleId: com.dev.ontari