name: ontari_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'
dependencies:
  get: ^5.0.0-release-candidate-4
  cloud_firestore: ^4.5.0
  connectivity_plus: ^3.0.0
  cupertino_icons: ^1.0.5
  dio: ^5.2.0+1
  equatable: ^2.0.5
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  firebase_crashlytics: ^3.3.2
  firebase_storage: ^11.2.2
  flutter_screenutil: ^5.6.1
  flutter_svg: ^2.0.5
  get_it: ^7.6.0
  google_fonts: ^4.0.3
  hive_flutter: ^1.1.0
  http_parser: ^4.0.2
  injectable: ^2.1.2
  json_annotation: ^4.8.1
  mime: ^1.0.4
  path: ^1.8.2
  path_provider: ^2.0.15
  device_info_plus: ^9.0.2
  timezone: ^0.9.2
  url_launcher: ^6.1.11
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
    
dev_dependencies: 
  build_runner: ^2.3.3
  flutter_flavorizr: ^2.1.4
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.0
  injectable_generator: ^2.1.5
  json_serializable: ^6.6.1
  flutter_test: 
    sdk: flutter
flutter: 
  assets: 
    - assets/images/
    - assets/icons/
    - assets/locales/
  uses-material-design: true
flutter_native_splash: 
  color: '#193D71'
  image: assets/images/ic_app_icon_large.png
  android_screen_orientation: locked
flutter_icons: 
  android: launcher_icon
  image_path: assets/images/ic_app_icon.png
  ios: true
  remove_alpha_ios: true
  min_sdk_android: 21
flavorizr: 
  ide: vscode
  app: 
    android: 
      flavorDimensions: flavor-type
    ios: null
  flavors: 
    prod: 
      app: 
        name: Ontari-Prod
        icon: assets/images/ic_app_icon.png
      android: 
        applicationId: com.prod.ontari
      ios: 
        bundleId: com.prod.ontari
        buildSettings: 
          FIREBASE_APPLE_APP_ID: 1:409239618751:ios:43ae91ea92d2a06297720a
    dev: 
      app: 
        name: Ontari-Dev
        icon: assets/images/ic_app_icon.png
      android: 
        applicationId: com.dev.ontari
      ios: 
        bundleId: com.dev.ontari
        buildSettings: 
          FIREBASE_APPLE_APP_ID: 1:409239618751:ios:b53ce2521cb6c83f97720a
flutter_gen: 
  output: lib/generated/
  integrations: 
    flutter_svg: true
get_cli:
  separator: .