name: ontari_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.3
  flutter_svg: ^2.0.5
  flutter_screenutil: ^5.6.1
  dio: ^5.2.0+1
  get_it: ^7.6.0
  injectable: ^2.1.2
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.2
  hive_flutter: ^1.1.0
  equatable: ^2.0.5
  auto_route: ^6.0.4
  firebase_core: ^2.8.0
  path: ^1.8.2
  firebase_crashlytics: ^3.3.2
  dartz: ^0.10.1
  connectivity_plus: ^3.0.0
  http_parser: ^4.0.2
  mime: ^1.0.4
  formz: ^0.6.0
  firebase_auth: ^4.6.2
  path_provider: ^2.0.15
  easy_localization: ^3.0.1
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter 

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  flutter_flavorizr: ^2.1.4
  json_serializable: ^6.6.1
  injectable_generator: ^2.1.5
  flutter_gen_runner: ^5.3.1
  auto_route_generator: ^6.0.4
  
  flutter_test:
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/locales/

flutter_native_splash:
  color: '#193D71'
  image: assets/images/ic_app_icon_large.png
  android_screen_orientation: locked
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/ic_app_icon.png"
  min_sdk_android: 21

flavorizr:
  app:
    android:
      flavorDimensions: flavor-type
    ios:
  ide: "vscode"
  flavors:
    prod:
      app:
        name: Ontari-Prod
        icon: assets/images/ic_app_icon.png
      android:
        applicationId: com.prod.ontari
      ios:
        bundleId: com.prod.ontari
    dev:
      app:
        name: Ontari-Dev
        icon: assets/images/ic_app_icon.png
      android:
        applicationId: com.dev.ontari
      ios:
        bundleId: com.dev.ontari

flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true
