name: flutter_clean_architech_bloc
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  flutter_svg: ^1.1.5


dev_dependencies:
  build_runner:
  flutter_flavorizr: ^2.1.4
  flutter_gen_runner: ^5.0.1
  flutter_native_splash: ^2.2.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

#Flutter gen
flutter_gen:
  output: lib/constants/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true
    assets:
      outputs:
        style: camel-case

flutter_native_splash:
  color: '#193D71'
  image: assets/images/ic_app_icon_large.png
  android_screen_orientation: locked

flavorizr:
  app:
    android:
      flavorDimensions: flavor-type
    ios:
  ide: "vscode"
  flavors:
    prod:
      app:
        name: Ontari-Prod
        icon: assets/images/ic_app_icon.png
      android:
        applicationId: com.prod.ontari
      ios:
        bundleId: com.prod.ontari
    dev:
      app:
        name: Ontari-Dev
        icon: assets/images/ic_app_icon.png
      android:
        applicationId: com.dev.ontari
      ios:
        bundleId: com.dev.ontari